/*
 * Constants.h
 *
 * Author: Adi Elbaz 206257313
 *         Yuval Ron 313584187
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

// Map
#define BLOW_ROBOT_FACTOR 2.5
#define MAP_ROTATION -30
#define ROBOT_SIZE 20
#define RESOLUTION_SIZE 5

// Waypoints
#define WAYPOINT_TOLERENCE 15
#define WAYPOINT_RANGE 2

// Robot
#define ROBOT_START_X 470
#define ROBOT_START_Y 470
#define GOAL_X 370
#define GOAL_Y 540
#define DELTA_ANGLE_TOL 20
#define MAX_MOVE_SPEED 0.4
#define MAX_TURN_SPEED 0.2
#define MIN_TURN_SPEED 0.1
#define YAW_TOLERANCE 1.05
#define MAX_WHEELS_ANGLE 45
#define MIN_WHEELS_ANGLE 2
#define FORWARD_SPEED_FACTOR 50

#define MIN_DISTANCE_FOR_FULL_SPEED 25

// Particle
#define TARGET_START_BELIEF 0.8f
#define STARTING_PARTICLES 99
#define BELIEF_NORMALIZATION 1.5
#define DISTANCE_THRESHOLD 1
#define YAW_THRESHOLD_DEGREES 120
#define MIN_BELIEF 0.3
#define BELIEF_BIRTH_THRESHOLD 0.8
#define MIN_PARTICLE_NUM 1
#define MAX_PARTICLE_NUM 300
#define PARTICLES_REMOVE 10
#define PARTICLE_BREED_NUM 3
#define PARTICLE_BREED_SPREAD 50
#define PARTICLE_YAW_BREED_SPREAD 10
#define NEAR_OBSTACLE_RADIUS 2

#endif  CONSTANTS_H_

